Modified to successfully  work with gradlew and airwallex-services

diff --git a/sti/bin/assemble b/sti/bin/assemble
--- a/sti/bin/assemble
+++ b/sti/bin/assemble
@@ -1,8 +1,7 @@
 #!/bin/bash
 . $(dirname $0)/functions
-
+GRADLE_USER_HOME=/opt/gradle
 HOME=/opt/app-root/src
-
 # we will move any code provided by s2i to here
 LOCAL_SOURCE_DIR=${HOME}/source
 mkdir -p $LOCAL_SOURCE_DIR
@@ -76,26 +75,37 @@ if [ -f "$LOCAL_SOURCE_DIR/pom.xml" ]; then
 elif [ -f "$LOCAL_SOURCE_DIR/build.gradle" ]; then
   # the subdirectory within LOCAL_SOURCE_DIR from where we should copy build
   # artifacts (*.war, *.jar)
-  ARTIFACT_DIR=${ARTIFACT_DIR:-build/libs}
+  ARTIFACT_DIR=${ARTIFACT_DIR:-${MODULE_DIR}/build/libs}
 
   echo "Building with gradle. $LOCAL_SOURCE_DIR/build.gradle found."
 
   pushd $LOCAL_SOURCE_DIR &> /dev/null
 
-  if [ -z "$BUILDER_ARGS" ]; then
-    export BUILDER_ARGS="build -x test"
-    # TODO: Specify setting file with -c sss
+  if [ -z "$MODULE_DIR" ]; then
+	echo "Environment variable MODULE_DIR is required"
+	exit 1
   fi
 
-  echo "Found gradle.build ... attempting to build with './gradlew -s ${BUILDER_ARGS}'"
+  if [ -z "$BUILDER_ARGS" ]; then
+    export BUILDER_ARGS="clean bootrepackage -x test -p $MODULE_DIR"
+    # TODO: Specify setting file with -c sss
+  fi
+ 
+  if [ -z "$APP_SUFFIX" ]; then
+	echo "Environment variable APP_SUFFIX is requied"
+	exit 1
+  fi
 
-  echo "Gradle version:"
-  ./gradlew --version
+  echo "Found gradle.build ... attempting to build with '${LOCAL_SOURCE_DIR}/gradlew ${BUILDER_ARGS} ${EXTRA_ARGS} -Dfile.encoding=UTF-8 '"
+echo "Gradle version:"
+  $LOCAL_SOURCE_DIR/gradlew --version
 
   # Execute the actual build
-  ./gradlew -s $BUILDER_ARGS
+  $LOCAL_SOURCE_DIR/gradlew $BUILDER_ARGS
 
   ERR=$?
+
+ls -la build/libs
   if [ $ERR -ne 0 ]; then
     echo "Aborting due to error code $ERR from Gradle build"
     exit $ERR
@@ -108,7 +118,7 @@ elif [ -f "$LOCAL_SOURCE_DIR/build.gradle" ]; then
 
 
   # clean up after maven
-  ./gradlew clean
+  $LOCAL_SOURCE_DIR/gradlew clean
 #  if [ -d "$HOME/.m2/repository" ]; then
 #    rm -r "$HOME/.m2/repository"
 #  fi
